branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
language: node_js
node_js:
  - stable
  - 6
  - 5
  - 4
sudo: false
before_install: npm i -g npm@latest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0418713e51ac049564a
    on_success: always
    on_failure: change
    on_start: never
addons:
  code_climate:
    repo_token: 5fb5515c61643d8dd2f603726d5f92fb728a0ca42e9f81c2090dffd0afc3aa7c
after_script:
  - "[ $TRAVIS_NODE_VERSION = stable ] && nyc report --reporter=text-lcov | codeclimate-test-reporter"

